### ISSUE TITLE
I have completely violated the terms of this project for the betterment of mankind

### ISSUE THREAD

**Issue by hopeseekr** [RayPS/Read-Only-License#1]
Hi,

Your package currently has a serious legal loophole.

In order to use your license in someone else's project, they have to actually violate this license :-(

I have done so over at [phpexpertsinc/Read-Only-License](https://github.com/phpexpertsinc/Read-Only-License) :-( and in several of my projects already.

You can either ignore me, sue me, grant me some rights to fork, reuse, and sublicense, or open source this license by adding a LICENSE.md for something like the MIT license.

**Comment by RayPS** [comment]
Hi,
Thanks for your interest to ROL.
This license is just a simple statement for some of my own GitHub repos, I made it a 'license' so I don't have to copy and paste to every repo and also keep it up to date. I take my own responsible for any loopholes.
ROL is also licensed with ROL, you should not folk and make modification, but instead, you get the idea of ROL and write your own ROL that suits yourself and your projects. But I will ignore you at this moment.

**Comment by Leialoha** [comment]
<deleted>
