### ISSUE TITLE
Is the licencese itself can be copied?

### ISSUE THREAD

**Issue by NicklausBrain** [RayPS/Read-Only-License#3]

**Comment by NicklausBrain** [comment]
@RayPS this is really a nice try, But what about the license itself. Can it be copied or modified?
Perhaps it makes sense to specify that the license text itself is distributed under MIT/GNU?

**Comment by RayPS** [comment]
Thanks for your interest in ROL.
Unfortunately I don't want anyone to use ROL directly as it may change at anytime.
You may want to make your own similar license that fits your needs as I've shared the idea of ROL here.
Sorry for the inconvenience.
